title: "Jeff Thomas"
author: "Jeff Thomas"
description: "University of Bellevue - Data Science"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show social sites in footer
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "aboutme.md", title: "About Me"}
  - {file: "projects.html", title: "Projects"}
  - {<embed src="Jeff_Resume.pdf" type="application/pdf"/>, title: "Resume"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:trade4huskers@hotmail.com"}
  - {title: Github, icon: github, url: "https://trade4huskers.github.io"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/jeff-thomas-8383a845/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
